parameters:
    pamelding:
        starter: 23.10.YYYY
        startdato: 23. oktober
    standardbilder:
        person: http://grafikk.ukm.no/placeholder/person.jpg
    hvaerukm:
        slogan: Der vi møtes, inspirerer, utfordrer og skaper sammen
        kort: >
            Ønsker du å skape noe, møte likesinnede og utvikle talentet ditt? 
            UKM er en møteplass for ungdom og kultur, der vi skaper noe sammen.
            <br /><br />
            Her kan du vise frem det du brenner for, eller hjelpe andre å bli sett. 
            I UKM er alle kulturelle uttrykk velkomne, enten det er sang, 
            fotokunst, cosplay eller moderne dans.
            <br /><br />
            Vi er her for å gi deg muligheten til å drive med det som interesserer deg! 
            Kanskje oppdager du også noe nytt? Hos oss kan du være den du vil.
        lesmer: //ukm.no/hva-er/
    organisasjonen:
        slogan: UKM skal inspirere ungdom til personlig utvikling, kulturell fordypning, dedikasjon og øving
    facebook:
        app_id: 141016739323676
        admins: 597605662
    google:
        site_verification: 'dD8sAwp7X8mpu2PN1iu4C3VWEDS8sMxYUavoVBrmnek'
        analytics: 
            main: 'UA-46216680-1'
    SEOdefaults:
        author: UKM
        site_name: UKM.no
        title: Ung Kultur Møtes
        image:
            url: http://grafikk.ukm.no/festivalen/2017/festival_pre_lg.jpg
            type: image/jpeg
            width: 1500
            height: 628
        type: website
    SEOdefaultsApp:
    firenullfire:
        title: Siden finnes ikke!
        text: Siden du søker har enten blitt flyttet eller aldri eksistert (spooky)
    
    logoer:
        ukm:
            navn: UKM-logo
            utgaver:
                primar:
                    url: '//grafikk.ukm.no/profil/logoer/UKM_logo_sort_0300.png'
                    navn: Sort
                    class:
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_sort.pdf'
                            navn: PDF (vektorbasert)
                        -
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_sort_2500.png'
                            navn: PNG (2500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_sort_1500.png'
                            navn: PNG (1500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_sort_0500.png'
                            navn: PNG (500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_sort_0300.png'
                            navn: PNG (300px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_sort_0100.png'
                            navn: PNG (100px)
                sekundar:
                    url: '//grafikk.ukm.no/profil/logoer/UKM_logo_hvit_0300.png'
                    navn: Hvit
                    class: background-color-primary-light
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_hvit.pdf'
                            navn: PDF (vektorbasert)
                        -
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_hvit_2500.png'
                            navn: PNG (2500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_hvit_1500.png'
                            navn: PNG (1500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_hvit_0500.png'
                            navn: PNG (500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_hvit_0300.png'
                            navn: PNG (300px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_hvit_0100.png'
                            navn: PNG (100px)
                spesial:
                    url: '//grafikk.ukm.no/profil/logoer/UKM_logo_bla_0300.png'
                    navn: Blå (spesialutgave)
                    class: 
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_bla.pdf'
                            navn: PDF (vektorbasert)
                        -
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_bla_2500.png'
                            navn: PNG (2500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_bla_1500.png'
                            navn: PNG (1500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_bla_0500.png'
                            navn: PNG (500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_bla_0300.png'
                            navn: PNG (300px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/UKM_logo_bla_0100.png'
                            navn: PNG (100px)

        ukmmedia:
            navn: UKM Media-logo
            utgaver:
                primar:
                    url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_sort_0300.png'
                    navn: Sort
                    class:
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_sort.pdf'
                            navn: PDF (vektorbasert)
                        -
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_sort_2500.png'
                            navn: PNG (2500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_sort_1500.png'
                            navn: PNG (1500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_sort_0500.png'
                            navn: PNG (500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_sort_0300.png'
                            navn: PNG (300px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_sort_0100.png'
                            navn: PNG (100px)
                sekundar:
                    url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_hvit_0300.png'
                    navn: Hvit
                    class: background-color-primary-light
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_hvit.pdf'
                            navn: PDF (vektorbasert)
                        -
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_hvit_2500.png'
                            navn: PNG (2500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_hvit_1500.png'
                            navn: PNG (1500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_hvit_0500.png'
                            navn: PNG (500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_hvit_0300.png'
                            navn: PNG (300px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/media/UKM_Media_logo_hvit_0100.png'
                            navn: PNG (100px)
        
        ukmressurs:
            navn: UKM-ressurslogo
            utgaver:
                primar:
                    url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_sort_0300.png'
                    navn: Sort
                    class:
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_sort.pdf'
                            navn: PDF (vektorbasert)
                        -
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_sort_2500.png'
                            navn: PNG (2500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_sort_1500.png'
                            navn: PNG (1500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_sort_0500.png'
                            navn: PNG (500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_sort_0300.png'
                            navn: PNG (300px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_sort_0100.png'
                            navn: PNG (100px)
                sekundar:
                    url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_hvit_0300.png'
                    navn: Hvit
                    class: background-color-primary-light
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_hvit.pdf'
                            navn: PDF (vektorbasert)
                        -
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_hvit_2500.png'
                            navn: PNG (2500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_hvit_1500.png'
                            navn: PNG (1500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_hvit_0500.png'
                            navn: PNG (500px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_hvit_0300.png'
                            navn: PNG (300px)
                        - 
                            url: '//grafikk.ukm.no/profil/logoer/ressurs/UKM-ressurs_hvit_0100.png'
                            navn: PNG (100px)
    grafiske_elementer:
        bobla:
            navn: UKM-bobla
            utgaver:
                bla:
                    url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_bla_0300.png'
                    navn: Blå
                    class:
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_bla.pdf'
                            navn: PDF (vektorbasert)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_bla_2500.png'
                            navn: PNG (2500px)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_bla_1500.png'
                            navn: PNG (1500px)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_bla_0500.png'
                            navn: PNG (500px)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_bla_0300.png'
                            navn: PNG (300px)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_bla_0100.png'
                            navn: PNG (100px)
                hvit:
                    url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_hvit_0300.png'
                    navn: Hvit
                    class: background-color-primary-light
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_hvit.pdf'
                            navn: PDF (vektorbasert)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_hvit_2500.png'
                            navn: PNG (2500px)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_hvit_1500.png'
                            navn: PNG (1500px)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_hvit_0500.png'
                            navn: PNG (500px)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_hvit_0300.png'
                            navn: PNG (300px)
                        - 
                            url: '//grafikk.ukm.no/profil/bobla/UKM-bobla_hvit_0100.png'
                            navn: PNG (100px)
        plakater:
            navn: Plakater
            utgaver:
                boble:
                    url: '//grafikk.ukm.no/profil/plakater/UKM-plakat_boble.png'
                    navn: Plakat med boble
                    class: 
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/plakater/UKM-plakat_boble.pdf'
                            navn: PDF (vektorbasert)
                pamelding:
                    url: '//grafikk.ukm.no/profil/plakater/UKM-plakat_pamelding.png'
                    navn: Påmeldingsplakat
                    class: 
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/plakater/UKM-plakat_pamelding.pdf'
                            navn: PDF (vektorbasert)
        flyere:
            navn: Flyerer
            utgaver:
                flyer:
                    url: '//grafikk.ukm.no/profil/flyere/UKM-flyer.png'
                    navn: Flyer
                    class: 
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/flyere/UKM-flyer_bokmal.pdf'
                            navn: Bokmål (PDF)
                        - 
                            url: '//grafikk.ukm.no/profil/flyere/UKM-flyer_nynorsk.pdf'
                            navn: Nynorsk (PDF)
                        - 
                            url: '//grafikk.ukm.no/profil/flyere/UKM-flyer_nordsamisk.pdf'
                            navn: Nordsamisk (PDF)
                        - 
                            url: '//grafikk.ukm.no/profil/flyere/UKM-flyer_sorsamisk.pdf'
                            navn: Sørsamisk (PDF)
                        - 
                            url: '//grafikk.ukm.no/profil/flyere/UKM-flyer_lulesamisk.pdf'
                            navn: Lulesamisk (PDF)
        brosjyrer:
            navn: Brosjyrer
            utgaver:
                flyer:
                    url: '//grafikk.ukm.no/profil/flyere/UKM-internasjonal-brosjyre.png'
                    navn: Internasjonal brosjyre
                    class: 
                    filer:
                        - 
                            url: '//grafikk.ukm.no/profil/flyere/UKM-internasjonal-brosjyre.pdf'
                            navn: PDF